// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/aury-cli/CLITerminal.tsx": () => import("../components/mockups/aury-cli/CLITerminal.tsx"),
  "./components/mockups/aury-gui/GUIDashboard.tsx": () => import("../components/mockups/aury-gui/GUIDashboard.tsx")
};
